/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Bidet_3957100H_1001_1: THREE.Mesh
    Bidet_3957100H_1001_2: THREE.Mesh
    Bidet_3957100H_1001_3: THREE.Mesh
  }
  materials: {
    ['diffuse_0.001']: THREE.MeshStandardMaterial
    ['Polierter Edelstahl.001']: THREE.MeshStandardMaterial
    ['Porzellan.001']: THREE.MeshStandardMaterial
  }
}

export default function Model({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('models/Bidet.gltf') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Bidet_3957100H_1001_1.geometry} material={materials['diffuse_0.001']} />
        <mesh geometry={nodes.Bidet_3957100H_1001_2.geometry} material={materials['Polierter Edelstahl.001']} />
        <mesh geometry={nodes.Bidet_3957100H_1001_3.geometry} material={materials['Porzellan.001']} />
      </group>
    </group>
  )
}

useGLTF.preload('/Bidet.gltf')
